version: "3"

services:
  rabbitmq:
    image: rabbitmq:latest
    privileged: true
    container_name: rabbitmq
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 3s
    networks:
      - backend


volumes:
  postgres-db:

networks:
  backend:
